const goals =[
    {title:"Have a get together at my apartment.",
        description:"Since moving I have been craving community. This way I remind myself that I don't just happen to fall into community but that I can start it myself.",
        status:"Not Started"},
    {title:"Finish (3) a novel every 150 days.",
        description:"I appreciate the art of writing. Being able to read a book from start to finish is also something I have greatly admired. Although my preference would be to start consistently reading, I think it is somewhat a lost art.",
        status:"Not Started"},
    {title:"Invest 1,000 USD in a high risk yet well calculated investment.",
        description:"America has so much opportunity to make money through investment, so without spending too much it would be a loss to not at least learn how to invest and multiply my money with the resources I am lucky to have available to me.",
        status:"Not Started"},
    {title:"Donate my time to a cause I feel passionate about, at least 3 times.",
        description:"Part of why this is on the list is to find what, besides myself, I find important enough to do for others without anyone asking or any incentive. I want to explore what that might be. Something selfless. I think it is a great way to know myself better.",
        status:"Not Started"},
    {title:"Save at least 6 months' worth (25,000) of emergency fund.",
        description:"I know money is freedom, and having enough that I don't feel tied down would be important for me to always feel free. Again, being in a position where I can save this much money is such a privilege. It would be a disservice to myself not to have enough saved away for a day when things aren't as bright.",
        status:"Not Started"},
    {title:"Spend a weekend away from network with loved one(s).",
        description:"It's so loud with all the technology and all the urges to know what is happening. I am reminded of the times when we would visit my grandmother and father, and all we would do was lay their working, but also just being together. So what would make this so much more would be to do it with people I love.",
        status:"Not Started"},
    {title:"Take a culinary class focused on how to eat healthy.",
        description:"Food will always be something I enjoy and feel brings people together. Spending the time to learn the art of cooking would help build up a skill that I will use forever, and I feel spending the money, time and effort is a reflection of that appreciation for food.",
        status:"Not Started"},
    {title:"Ask for a raise/a promotion at work.",
        description:"I lean heavily on people seeing my good work and that being enough. I feel it is important that I learn to advocate for myself and what I want, so this should not be for the sake of it but should be something meaningful for me. In a year and a half my visa will be up, what then? I need to slowly start the conversation and ask for what I want and deserve.",
        status:"Not Started"},
    {title:"Find a community to network and grow my career with.",
        description:"It is very much in line with learning from others. I initially wanted a mentor, and I think I still do, but I think finding people that are learning with me would be more impactful for my growth. And so taking the time to meet different people and share our journey and learning is important to me.",
        status:"Not Started"},
    {title:"Share 10 short stories to a website or just with Kondwani.",
        description:"I have always appreciated writing. When I was in my teens I wrote so many short poems. It was an outlet for all my many emotions. Spending the time now before my 30th to write feels like homage to the 15-year-old that had so many feelings to navigate through.",
        status:"Not Started"},
    {title:"Spend 1-on-1 time with my family.",
        description:"Having spent all of my time away from home since I was 12, this, albeit small, is something important to knowing my family and siblings. Everyone, all 8 of them, deserves 1-on-1 time with me.",
        status:"Not Started"},
    {title:"Exercise consistently for 6 months.",
        description:"It is such a hard thing to commit to for me, yet so many people do. This is here for a lot of reasons: 1. To help with my fitness levels. It would be nice to not shy away from a hill or stairs. 2. I have gained a lot of weight that is weighing me down, and when I have kids I want to play with them. 3. I wanna look hot for my husband.",
        status:"Not Started"},
    {title:"Pick a diet and stick to it for 6 months.",
        description:"Working out keeps my muscles fit, my diet heals my whole body, and a healthy body is a happy one... I hope. Well, if I can't at least keep such simple promises to myself, all hope is lost.",
        status:"Not Started"},
    {title:"Track every dollar spent for a month.",
        description:"Finances always start with awareness. I want to be aware of my expenses to make better financial decisions every chance I get, and the first step is knowing what I spend my money on.",
        status:"Not Started"},
    {title:"Run a 5K.",
        description:"I want to do this because I am scared I can't and feel I should be able to. Maybe there is something to enjoy about running and doing a 5K. Training for it is one way to know.",
        status:"Not Started"},
    {title:"Get a full physical.",
        description:"Knowledge is power only if it is used. I have gotten a physical check-up a couple of times. I would like to do one before my 30th. Also check my fertility, wanna have some babies haha.",
        status:"Not Started"},
    {title:"Go no screen for a week after dinner.",
        description:"This is to help see the benefit to my sleep. I want to do it with my husband, and potentially it will allow me to read more.",
        status:"Not Started"},
    {title:"Learn a language to converse.",
        description:"I have started learning a new language on two occasions. Because I am in the US and could probably practice it more, I will try to learn Spanish. I think it would be very rich to know more than my mother tongue and English.",
        status:"Not Started"},
    {title:"Earn a certification to help my career.",
        description:"I still need more time to think of what exactly, but as a lifelong learner who is somewhat interested in a successful career, I would like to take the time to learn something I can use at my job.",
        status:"Not Started"},
    {title:"Spend a full weekend camping off the grid.",
        description:"With nature, with nothing but people and basic needs, to reset my nervous system and appreciate the simple things in life.",
        status:"Not Started"},
    {title:"Visit a continent I have never been to before.",
        description:"Travelling has always helped broaden my view of the world, granted I am more of a vacationer than a traveller. Visiting a fifth continent would be a great adventure. I also want to maximize it and plan out something fun for every day I am there, considering I usually just go and wing it on most trips.",
        status:"Not Started"},
    {title:"Take an overnight train to a new city.",
        description:"I think this will be such a fun experience. It feels old-worldly. I wonder if I should do it in Sweden, since they have good overnight trains, or maybe visit another city in California. Either way, the experience should be fun.",
        status:"Not Started"},
];